/**
 * PromptDashboardCanvas — Figma-matched card grid with flip interaction.
 *
 * Source: Figma Wireframes v.4b (20UPR2KQMsbAxlo5NJb1se), node 40000640:17952.
 * Full architecture story → storybook: CardDesignSystem.stories.tsx
 *
 * Quick rules for this file:
 *   - Every element carries a data-node-id linking to its Figma node.
 *   - DO NOT remove data-node-ids — they are the bridge to AI assembly.
 *   - FIGMA.colors token block is the single source of truth for extracted colors.
 *   - TODO markers flag CSS approximations awaiting Figma SVG asset swap.
 *
 * Built 2026-07-13. Designer owns the vision; code follows the design.
 */

import React, { useState, useEffect, useRef, useCallback } from "react";
import { FlipCard } from "./FlipCard";
import { FeaturedCard } from "./FeaturedCard";
import imgImage359 from "@/assets/5e6d8c1ff1f88eac724c57dccba01dde4c5a1bba.png";
import imgImage390 from "@/assets/a0c698671eb795bc84024e87ad7c0b231c53115c.png";
import moleculeLogo from "@/assets/Molecule_fill.svg";
import { StorybookDocCard } from './StorybookDocCard';
import { STORYBOOK_DOCS, StorybookDoc } from '@/shared/storybookDocRegistry';
// Lit agent-card is auto-registered via side-effect import in main.tsx

// ═══════════════════════════════════════════════════════════════════════════════
// FIGMA DESIGN SYSTEM — Card Component Library
// Source: Figma Wireframes v.4b — SCE Enterprise AI Prompt Platform
// File:   20UPR2KQMsbAxlo5NJb1se
// Node:   40000640:17952 (Frame 886929 — Dashboard card grid)
//
// Every sub-component maps 1:1 to a Figma node via data-node-id.
// These IDs are the source of truth for AI-driven design assembly.
// DO NOT remove or change data-node-id attributes without updating Figma.
// ═══════════════════════════════════════════════════════════════════════════════

// ── Design tokens extracted from Figma variable definitions ───────────────────
// Figma node: 40000640:17952 variable defs
const FIGMA = {
  colors: {
    accent_orange:   "#FB8D67",  // Title accent — Figma node 40000640:16679
    accent_yellow:   "#F6C031",  // Title accent variant — Figma node 40000640:17678
    accent_teal:     "#8EC1B3",  // Approved status, template border — Figma node 40000640:16694
    status_pending:  "#672223",  // Pending status text — Figma node 40000640:17689
    pill_border:     "rgba(74,164,144,0.5)", // Version pill border — Figma node 40000640:16693
    avatar_border:   "#6A9C9E",  // Avatar border ring — Figma node 40000640:16689
    bottom_overlay:  "rgba(0,0,0,0.60)", // Bottom gradient start — Figma node imgRectangle2
    card_shadow:     "0px 4px 4px 0px rgba(0,0,0,0.25)", // Card shadow — Figma node 40000640:16643
    white:           "#FFFFFF",
    text_muted:      "#33363F",  // Line_icon token
  },
  // Card background gradient presets — extracted from Figma card imagery
  // TODO: Replace with actual imgGroup50 / imgGroup97 / imgFrame8815 SVG assets
  // when the svg-hju19.tsx module is generated by Figma Dev Mode export.
  cardGradients: [
    "from-[#0F3D4B] via-[#173A43] to-[#1B2F3A]",
    "from-[#1A4A5A] via-[#14323C] to-[#1C2F38]",
    "from-[#0E3A45] via-[#153741] to-[#1A2E36]",
    "from-[#11404F] via-[#183B46] to-[#1D313B]",
    "from-[#0C3540] via-[#14333E] to-[#192B34]",
  ],
  titleAccents: ["#FB8D67", "#F6C031", "#8EC1B3", "#FFFFFF"],
} as const;

// ═══════════════════════════════════════════════════════════════════════════════
// CARD SUB-COMPONENTS — Each maps to a specific Figma node
// These are the atomic building blocks of the card design system.
// AI assembly tools reference these by data-node-id to compose cards.
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * CardCategory — The eyebrow label above the title.
 * Figma node: 40000640:16680
 * Spec: Inter Medium 12px, #FFFFFF, 20px height, 199px width
 * Position: left 66.89px, top 21px (from card top, vertically centered)
 */
function CardCategory({ label }: { label: string }) {
  if (!label) return null;
  return (
    <p
      data-node-id="40000640:16680"
      data-name="CardCategory"
      className="absolute left-[66.89px] top-[21px] -translate-y-1/2 h-[20px] w-[199px] 
                 font-['Inter:Medium'] font-medium text-[12px] text-white leading-[normal]"
    >
      {label}
    </p>
  );
}

/**
 * CardTitle — Main headline in white Inter Bold.
 * Figma node: 40000225:12840
 * Exact Figma Tailwind: font-['Inter:Bold'] font-bold text-[18px] text-white 
 *   leading-[24px] h-[41px] left-[20px] top-[55px] w-[247px] whitespace-pre-wrap
 */
function _CardTitle({ text }: { text: string }) {
  return (
    <p
      data-node-id="40000225:12840"
      data-name="CardTitle"
      className="[word-break:break-word] absolute font-['Inter:Bold'] font-bold h-[41px] leading-[24px] left-[20px] 
                 not-italic text-[18px] text-white top-[55px] w-[247px] whitespace-pre-wrap"
    >
      {text}
    </p>
  );
}

/**
 * CardSubtitle — Accent-colored subtitle line.
 * Figma node: 40000225:12822
 * Exact Figma Tailwind: font-['Inter:Bold'] font-bold text-[#f6c031] text-[14px]
 *   h-[30px] left-[63.89px] top-[27px] w-[193px]
 */
function _CardSubtitle({ text }: { text: string }) {
  return (
    <p
      data-node-id="40000225:12822"
      data-name="CardSubtitle"
      className="-translate-y-1/2 [word-break:break-word] absolute flex flex-col font-['Inter:Bold'] font-bold 
                 h-[30px] justify-center leading-[0] left-[63.89px] not-italic text-[#f6c031] text-[14px] 
                 top-[27px] w-[193px]"
    >
      <span className="leading-[normal]">{text}</span>
    </p>
  );
}

/**
 * CardDescription — Body text in Open Sans.
 * Figma node: 40000225:12834
 * Exact Figma Tailwind: font-['Inter:Regular'] h-[80px] left-[19px] top-[101px] w-[247px]
 *   Inner: Open Sans SemiBold 13px white leading-[20px] wdth 100
 */
function _CardDescription({ text }: { text?: string }) {
  return (
    <div
      data-node-id="40000225:12834"
      data-name="CardDescription"
      className="[word-break:break-word] absolute font-['Inter:Regular'] font-normal h-[80px] leading-[0] 
                 left-[19px] not-italic overflow-hidden text-[#2a2836] text-[0px] text-ellipsis 
                 top-[101px] w-[247px] whitespace-pre-wrap"
    >
      {text ? (
        <p className="mb-0 text-[12px]">
          <span className="font-['Open_Sans:SemiBold'] font-semibold leading-[20px] text-[13px] text-white"
                style={{ fontVariationSettings: '"wdth" 100' }}>
            {text}
          </span>
        </p>
      ) : null}
    </div>
  );
}

/**
 * CardTags — Green hashtag row.
 * Figma node: 40000225:12833
 * Exact Figma Tailwind: font-['Inter:Semi_Bold'] font-semibold text-[#99ffa9] text-[14px]
 *   h-[20px] left-[19.89px] top-[239px] w-[222px]
 */
function _CardTags({ tags }: { tags?: string }) {
  if (!tags) return null;
  return (
    <p
      data-node-id="40000225:12833"
      data-name="CardTags"
      className="[word-break:break-word] absolute font-['Inter:Semi_Bold'] font-semibold h-[20px] leading-[20px] 
                 left-[19.89px] not-italic overflow-hidden text-[#99ffa9] text-[14px] text-ellipsis 
                 top-[239px] w-[222px] whitespace-pre"
    >
      {tags}
    </p>
  );
}

/**
 * CardBottomOverlay — Gradient overlay at card bottom containing user info + metrics.
 * Figma node: 40000640:16683 (container), 40000640:16685 (imgRectangle2 background)
 * Spec: Starts at top 255px, full width, contains avatar, username, team, version badge, likes, star
 * Background: imgRectangle2 — currently approximated with gradient; TODO: swap for actual SVG asset
 */
function _CardBottomOverlay({ children }: { children: React.ReactNode }) {
  return (
    <div
      data-node-id="40000640:16683"
      data-name="CardBottomOverlay"
      className="absolute left-0 right-0 bottom-0"
      style={{ top: "255px" }}
    >
      {/* Background rectangle — Figma node 40000640:16685 (imgRectangle2) */}
      <div
        data-node-id="40000640:16685"
        data-name="CardBottomBackground"
        className="absolute inset-0 bg-gradient-to-t from-black/60 via-black/30 to-transparent rounded-b-[10px]"
      />
      {children}
    </div>
  );
}

/**
 * CardAvatar — User avatar image.
 * Figma node: 40000640:16689
 * Spec: 39×38px, rounded-full (or rounded-[100px] per some card variants),
 *       border #6A9C9E, positioned left 14.26px, top 263px (relative to card)
 * Uses imgImage360 asset from Figma export.
 */
function _CardAvatar({ initial }: { initial: string }) {
  return (
    <div
      data-node-id="40000640:16689"
      data-name="CardAvatar"
      className="absolute left-[14.26px] top-[263px] w-[39px] h-[38px] rounded-full 
                 border border-[#6A9C9E] bg-[#2A5A5A] flex items-center justify-center"
    >
      <span className="text-white text-[14px] font-['Inter:Bold'] font-bold">
        {initial}
      </span>
    </div>
  );
}

/**
 * CardUsername — @handle display.
 * Figma node: 40000640:16688
 * Spec: Inter Semi Bold 13px, #FFFFFF, left 63px, top 261px, max-width 189px, truncate
 */
function _CardUsername({ username }: { username: string }) {
  if (!username) return null;
  return (
    <p
      data-node-id="40000640:16688"
      data-name="CardUsername"
      className="absolute left-[63px] top-[261px] 
                 font-['Inter:Semi_Bold'] font-semibold text-[13px] text-white 
                 leading-[20px] overflow-hidden text-ellipsis whitespace-nowrap max-w-[189px]"
    >
      @{username}
    </p>
  );
}

/**
 * CardTeamName — Team/account line below username.
 * Figma node: 40000640:16686
 * Spec: Inter Medium 12px, #FFFFFF, left 63.26px, top 285px, max-width 204px, truncate
 */
function _CardTeamName({ name }: { name?: string }) {
  if (!name) return null;
  return (
    <p
      data-node-id="40000640:16686"
      data-name="CardTeamName"
      className="absolute left-[63.26px] top-[285px]
                 font-['Inter:Medium'] font-medium text-[12px] text-white
                 leading-[16px] overflow-hidden text-ellipsis whitespace-nowrap max-w-[204px]"
    >
      {name}
    </p>
  );
}

/**
 * CardLevelBadge — "LEVEL X" label (right-aligned).
 * Figma node: 40000640:16687
 * Spec: Inter Bold 13px, #FFFFFF, transform translateX(-100%), left 262px, top 259px
 * NOTE: This element is present in the Figma design for featured cards;
 *       it may be conditionally rendered based on card type or level metadata.
 */
function _CardLevelBadge({ level }: { level?: number }) {
  if (!level) return null;
  return (
    <p
      data-node-id="40000640:16687"
      data-name="CardLevelBadge"
      className="absolute -translate-x-full left-[262px] top-[259px]
                 font-['Inter:Bold'] font-bold text-[13px] text-white text-right
                 leading-[20px] h-[23px] w-[75px]"
    >
      LEVEL {level}
    </p>
  );
}

/**
 * CardVersionBadge — Version number + status pill.
 * Figma node: 40000640:16692 (container), 40000640:16693 (pill background), 40000640:16694 (text)
 * Spec: Container 160×45px, left 5.89px, top 307px
 *        Pill: border rgba(74,164,144,0.5), rounded-[20px], 27px height, 136px width
 *        Text: "v. {n} | {status}" — Inter Medium 14px + Inter Bold 14px, white
 */
function _CardVersionBadge({ version, status }: { version: number; status: string }) {
  const isApproved = status === "Approved" || status === "approved";
  const statusColor = isApproved ? FIGMA.colors.accent_teal : FIGMA.colors.accent_orange;
  return (
    <div
      data-node-id="40000640:16692"
      data-name="CardVersionBadge"
      className="absolute left-[5.89px] top-[307px] h-[45px] w-[160px] rounded-[5px]"
    >
      {/* Pill background — Figma node 40000640:16693 */}
      <div
        data-node-id="40000640:16693"
        data-name="CardVersionPill"
        className="absolute left-0 top-[15px] h-[27px] w-[136px]
                   border border-[rgba(74,164,144,0.5)] rounded-[20px]"
      />
      {/* Pill text — Figma node 40000640:16694 */}
      <div
        data-node-id="40000640:16694"
        data-name="CardVersionText"
        className="absolute left-[12px] top-[29px] -translate-y-1/2 
                   font-['Inter:Medium'] font-medium text-[14px] text-white leading-[normal] h-[28px] w-[153px]"
      >
        <span>v. {version}</span>
        <span className="mx-[4px] text-white/50">|</span>
        <span className="font-['Inter:Bold'] font-bold" style={{ color: statusColor }}>
          {status}
        </span>
      </div>
    </div>
  );
}

/**
 * CardThumbsUp — Like count + thumbs-up icon.
 * Figma nodes: 40000640:16696 (count), 40000640:16697 (icon)
 * Spec: Count: Inter Bold 13px white, right-aligned, left 242.89px, top 329px
 *        Icon: 22×22px, left 246.89px, top 324px
 * SVG icon uses Figma's Vector path (node I40000640:16697;1573:2352)
 */
function _CardThumbsUp({ count }: { count: number }) {
  return (
    <>
      {/* Like count — Figma node 40000640:16696 */}
      <p
        data-node-id="40000640:16696"
        data-name="CardLikeCount"
        className="absolute -translate-x-full left-[242.89px] top-[329px]
                   font-['Inter:Bold'] font-bold text-[13px] text-white
                   leading-[20px] h-[23px] w-[70px] text-right"
      >
        {count}
      </p>
      {/* Thumbs-up icon — Figma node 40000640:16697 */}
      <div
        data-node-id="40000640:16697"
        data-name="CardThumbsUpIcon"
        className="absolute left-[246.89px] top-[324px] w-[22px] h-[22px] text-white/70"
      >
        <svg className="w-full h-full" fill="currentColor" viewBox="0 0 24 24">
          <path d="M2 9.75C2 9.33579 2.33579 9 2.75 9H5.5V20H2.75C2.33579 20 2 19.6642 2 19.25V9.75ZM7 20V9L13.1793 2.17058C13.4935 1.85639 14 2.07714 14 2.51452V7.5H20.2763C21.1626 7.5 21.831 8.29151 21.6835 9.16411L20.1835 18.1641C20.0698 18.8371 19.4852 19.3359 18.8024 19.3359H7Z" />
        </svg>
      </div>
    </>
  );
}

/**
 * CardStar — Favorite/bookmark star icon.
 * Figma node: 40000640:16698
 * Spec: 25×25px, left 199.89px, top 323px
 * SVG icon uses Figma's Star--filled Vector path (node I40000640:16698;1572:6943)
 */
function _CardStar() {
  return (
    <div
      data-node-id="40000640:16698"
      data-name="CardStarIcon"
      className="absolute left-[199.89px] top-[323px] w-[25px] h-[25px] text-white/60"
    >
      <svg className="w-full h-full" fill="currentColor" viewBox="0 0 24 24">
        <path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z" />
      </svg>
    </div>
  );
}

/**
 * CardFavoriteIcon — Favorite/heart toggle (top-right area).
 * Figma node: 40000640:16690
 * Spec: 27×27px, left 237px, top 320px
 * NOTE: This is a separate favorite control from the star; positioned in the
 *       bottom-right quadrant. May be combined with star in future iterations.
 */
function _CardFavoriteIcon() {
  return (
    <div
      data-node-id="40000640:16690"
      data-name="CardFavoriteToggle"
      className="absolute left-[237px] top-[320px] w-[27px] h-[27px]"
    >
      <div className="absolute inset-0 bg-transparent mix-blend-multiply" />
    </div>
  );
}

/**
 * CardTopBadge — Top-left decorative badge icon.
 * Figma node: 40000640:16699
 * Spec: Uses imgImage390 asset (57×54px PNG). Positioned near top-left with slight offset.
 * Falls back to molecule-style dot cluster if asset not available.
 */
function _CardTopBadge() {
  return (
    <div
      data-node-id="40000640:16699"
      data-name="CardTopBadge"
      className="absolute left-[6.89px] top-0 w-[57px] h-[54px]"
    >
      {/* Molecule dot cluster — placeholder for imgImage390 asset */}
      {/* Figma node: 40000122:3323 (Molecule_fill icon) — composed of Ellipse 178-183 + Subtract */}
      <div className="absolute inset-[7.14%_9.09%_11.9%_13.64%] flex gap-[2.5px] items-start">
        <div className="w-[13px] h-[13px] rounded-full bg-white/30 mt-[12px]" />
        <div className="w-[10px] h-[10px] rounded-full bg-white/25 mt-[3px]" />
        <div className="w-[8px] h-[8px] rounded-full bg-white/20 mt-[5px]" />
      </div>
    </div>
  );
}

// ── Card category themes — exact Figma styling ──────────────────────────────
type CardCategory = 'ds' | 'learning' | 'graphics' | 'writing';
interface CardTheme {
  label: string;
  fill: string;
  titleColor: string;
  textColor: string;
  accentColor: string;
  barColor: string;
  statusColors: Record<string, string>;
  pillBorder: string;
  showPromptLabel: boolean;
  /** Model name displayed in Slot A (top-left) */
  modelName: string;
  /** MS connector badge — shown on DS cards (deprecated, replaced by Slot A modelName) */
  connector?: { label: string; bg: string; textColor: string };
}
const CARD_THEMES: Record<CardCategory, CardTheme> = {
  // Writing — bright olive green with dark text
  writing: {
    label: 'Writing',
    fill: '#658D1B',
    titleColor: '#fff',
    textColor: '#fff',
    accentColor: '#D29207',
    barColor: '#387386',
    statusColors: { Pending: '#672223', Approved: '#4ade80', Rejected: '#f87171' },
    pillBorder: 'rgba(74,164,144,0.5)',
    showPromptLabel: true,
    modelName: 'DeepSeek',
  },
  // Design System — exact match to CopilotAccountingCard Figma export
  ds: {
    label: 'Design System',
    fill: '#10455F',
    titleColor: '#fb8d67',
    textColor: '#fff',
    accentColor: '#FCCD3D',
    barColor: '#387386',
    statusColors: { Approved: '#4ade80', Pending: '#672223', Rejected: '#f87171' },
    pillBorder: 'rgba(74,164,144,0.5)',
    showPromptLabel: true,
    modelName: 'MS Copilot',
    connector: { label: 'MS Copilot', bg: '#0f4a8a', textColor: '#fff' },
  },
  // Learning — sage green
  learning: {
    label: 'Learning Module',
    fill: '#589678',
    titleColor: '#f6c031',
    textColor: '#fff',
    accentColor: '#FED141',
    barColor: '#387386',
    statusColors: { Approved: '#4ade80', Pending: '#672223', Rejected: '#f87171' },
    pillBorder: 'rgba(74,164,144,0.5)',
    showPromptLabel: false,
    modelName: 'Claude',
  },
  // Graphics — yellow-green, dark text
  graphics: {
    label: 'Graphics',
    fill: '#D3DF44',
    titleColor: '#484460',
    textColor: '#484460',
    accentColor: '#D29207',
    barColor: '#387386',
    statusColors: { Pending: '#672223', Approved: '#1a6b3c', Rejected: '#8b1a1a' },
    pillBorder: '#33363f',
    showPromptLabel: false,
    modelName: 'GPT-4o',
  },
};
const DEFAULT_THEME: CardTheme = CARD_THEMES.ds;

function resolveTheme(category?: string): CardTheme {
  const cat = (category || '').toLowerCase();
  if (cat.includes('design') || cat.includes('ds') || cat.includes('figma')) return CARD_THEMES.ds;
  if (cat.includes('learn') || cat.includes('train') || cat.includes('module')) return CARD_THEMES.learning;
  if (cat.includes('graphic') || cat.includes('image') || cat.includes('visual')) return CARD_THEMES.graphics;
  if (cat.includes('writ') || cat.includes('text') || cat.includes('report') || cat.includes('doc')) return CARD_THEMES.writing;
  return DEFAULT_THEME;
}

// Legacy array for backward compat — keep for any code still using colorIdx
const CARD_FILLS = ["#10455F", "#589678", "#D3DF44", "#FED141"];

// ── Relative timestamp formatter ─────────────────────────────────────────────
function formatRelativeTime(isoString?: string): string {
  if (!isoString) return '';
  const date = new Date(isoString);
  if (isNaN(date.getTime())) return '';
  const now = new Date();
  const today = new Date(now.getFullYear(), now.getMonth(), now.getDate());
  const target = new Date(date.getFullYear(), date.getMonth(), date.getDate());
  const diffDays = Math.round((today.getTime() - target.getTime()) / 86400000);
  const timeStr = date.toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit', hour12: true });

  if (diffDays === 0) return `Today · ${timeStr}`;
  if (diffDays === 1) return `Yesterday · ${timeStr}`;
  if (diffDays < 7) return `Last week`;
  return date.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
}

// ═══════════════════════════════════════════════════════════════════════════════
// DesignCard — EXACT FIGMA CODE from Group8747 (node 40000225:12689)
// Slot A (top-left 12px):  model name
// Slot B (top 14px bold):  category
// Slot C (top-right badge): timestamp (Today/Yesterday/Last week/date)
// Slot D (desc 18px bold):  title
// Background: CARD_FILLS color, #FFE9D4 stroke 0.5px, 278×359px
// Bottom overlay: #387386 fill
// ═══════════════════════════════════════════════════════════════════════════════
export function DesignCard({ title, category, description, username, teamName, version, status, likes, tags: _tags, comments: _comments, colorIdx: _colorIdx, modelName: explicitModelName, lastUsed, createdAt }: {
  title: string;
  category?: string;
  description?: string;
  username?: string;
  teamName?: string;
  version?: number;
  status?: string;
  likes?: number;
  tags?: string;
  comments?: number;
  colorIdx?: number;
  /** Slot A — model name (falls back to theme.modelName) */
  modelName?: string;
  /** Slot C — last-used timestamp (ISO string) */
  lastUsed?: string;
  /** Slot C fallback — created-at timestamp (ISO string) */
  createdAt?: string;
}) {
  const likeCount = likes ?? 0;
  const v = version ?? 1;
  const safeStatus = status || "Active";
  const theme = resolveTheme(category);
  const fill = theme.fill;
  const titleColor = theme.titleColor;
  const textColor = theme.textColor;
  const statusLookup = theme.statusColors;
  const _statusColor = statusLookup[safeStatus] ?? textColor;
  const isLightBg = fill === '#D3DF44';
  const displayModelName = explicitModelName || theme.modelName;
  const timestamp = formatRelativeTime(lastUsed || createdAt);

  return (
    <div
      data-node-id="40000236:9156"
      data-name="DesignCard"
      data-tag="agent-card"
      className="h-[359px] w-[278px] rounded-[10px] relative overflow-hidden"
      style={{ boxShadow: "0px 4px 4px 0px rgba(0,0,0,0.25)" }}
    >
      {/* Card background */}
      <svg className="absolute block inset-0 size-full" fill="none" preserveAspectRatio="none" viewBox="0 0 278.369 359">
        <path d="M10 0.25H268.369C273.754 0.25 278.119 4.61522 278.119 10V349C278.119 354.385 273.754 358.75 268.369 358.75H10C4.61523 358.75 0.25 354.385 0.25 349V10C0.250001 4.61522 4.61522 0.25 10 0.25Z" fill={fill} stroke="#FFE9D4" strokeWidth="0.5" />
      </svg>

      {/* Slot A — Model name (top left, 12px) */}
      <div className="-translate-y-1/2 [word-break:break-word] absolute flex flex-col font-['Inter:Medium',sans-serif] font-medium h-[20px] justify-center leading-[0] left-[66.89px] not-italic text-[12px] top-[21px] w-[199px]"
           style={{ color: textColor }}>
        <p className="leading-[normal]">{displayModelName}</p>
      </div>

      {/* Slot C — Timestamp badge (top right) */}
      {timestamp && (
        <div className="absolute right-[12px] top-[10px] px-[6px] py-[2px] rounded-[4px] text-[9px] font-bold tracking-wide"
             style={{ backgroundColor: 'rgba(255,255,255,0.12)', color: textColor, fontFamily: 'Inter, sans-serif' }}>
          {timestamp}
        </div>
      )}

      {/* Molecule overlay image — behind icon (DS cards only, matching CopilotAccountingCard Figma) */}
      {theme === CARD_THEMES.ds && (
        <div className="absolute left-[7px] top-0 w-[57px] h-[54px] overflow-hidden pointer-events-none">
          <img src={imgImage390} alt="" className="absolute h-[106%] left-0 max-w-none top-0 w-full" />
        </div>
      )}

      {/* Molecule icon — top left (Figma position: left-[19px] top-[9px]) */}
      <div className="absolute left-[19px] top-[9px]">
        <img alt="" className="w-[28px] h-[27px]" src={moleculeLogo} />
      </div>

      {/* Slot B — Category (top, 14px bold) */}
      <div className="-translate-y-1/2 [word-break:break-word] absolute flex flex-col font-['Inter:Bold',sans-serif] font-bold h-[36px] justify-center leading-[0] left-[64.89px] not-italic text-[14px] top-[38px] w-[199px]"
           style={{ color: titleColor }}>
        <p className="leading-[normal]">{category || theme.label}</p>
      </div>

      {/* Description */}
      <div className="[word-break:break-word] absolute font-['Inter:Regular',sans-serif] font-normal h-[180px] leading-[0] left-[14.89px] not-italic overflow-hidden top-[60px] w-[252px] whitespace-pre-wrap"
           style={{ color: textColor }}>
        <p className="mb-0 text-[12px]">
          <span className="[word-break:break-word] font-['Inter:Bold',sans-serif] font-bold leading-[22px] not-italic text-[18px]"
                style={{ color: textColor }}>
            {title}
          </span>
          {description && (
            <>
              <span className="leading-[10px]" style={{ color: textColor }}><br aria-hidden /></span>
              {theme.showPromptLabel && (
                <>
                  <span className="leading-[10px] text-[10px]" style={{ color: textColor, opacity: 0.55 }}>  </span>
                  <span className="leading-[10px] text-[11px] font-medium tracking-wide" style={{ color: textColor, opacity: 0.55 }}>
                    <br aria-hidden />##PROMPT##{'  '}
                  </span>
                </>
              )}
              <span className="[word-break:break-word] font-['Inter:Semi_Bold',sans-serif] font-semibold leading-[20px] not-italic text-[13px]"
                    style={{ color: textColor }}>
                {description}
              </span>
            </>
          )}
        </p>
      </div>

      {/* Bottom section — starts at top 255px */}
      <div className="absolute contents left-[1.89px] top-[255px]">
        <div className="absolute contents left-[1.89px] top-[255px]">
          {/* Bottom background */}
          <div className="absolute inset-[71.03%_0.89%_13.37%_0.68%]">
            <svg className="absolute block inset-0 size-full" fill="none" preserveAspectRatio="none" viewBox="0 0 274 56">
              <path d="M0 0H274V56H0V0Z" fill={isLightBg ? 'rgba(72,68,96,0.15)' : '#387386'} />
            </svg>
          </div>

          {/* Team name */}
          <p className="[word-break:break-word] absolute font-['Inter:Medium',sans-serif] font-medium h-[17px] leading-[16px] left-[65.26px] not-italic overflow-hidden text-[12px] text-ellipsis top-[285px] w-[204px] whitespace-nowrap"
             style={{ color: isLightBg ? '#484460' : '#fff' }}>
            {teamName || ""}
          </p>

          {/* LEVEL badge */}
          <p className="-translate-x-full [word-break:break-word] absolute font-['Inter:Bold',sans-serif] font-bold h-[23px] leading-[20px] left-[264px] not-italic text-[13px] text-right top-[259px] w-[75px]"
             style={{ color: isLightBg ? '#484460' : '#fff' }}>
            LEVEL {Math.min(v, 99)}
          </p>

          {/* @username */}
          <p className="[word-break:break-word] absolute font-['Inter:Semi_Bold',sans-serif] font-semibold h-[20px] leading-[20px] left-[65px] not-italic overflow-hidden text-[13px] text-ellipsis top-[261px] w-[189px] whitespace-nowrap"
             style={{ color: isLightBg ? '#484460' : '#fff' }}>
            {username ? `@${username}` : ""}
          </p>

          {/* Avatar — imgImage359 from Figma */}
          <div className="absolute h-[38px] left-[16.26px] top-[263px] w-[39px]" data-name="image 359">
            <img alt="" className="absolute block inset-0 max-w-none size-full" height="38" src={imgImage359} width="39" />
          </div>
        </div>

        {/* Favorite icon */}
        <div className="absolute left-[239px] overflow-clip size-[27px] top-[320px]" data-name="Favorite">
          <div aria-hidden className="absolute bg-[rgba(255,255,255,0)] inset-0 mix-blend-multiply pointer-events-none" />
        </div>

        {/* Version badge */}
        <div className="absolute h-[45px] left-[7.89px] rounded-[5px] top-[307px] w-[160px]">
          <div className="absolute border border-[rgba(74,164,144,0.5)] border-solid h-[27px] left-0 rounded-[20px] top-[15px] w-[136px]" />
          <div className="-translate-y-1/2 [word-break:break-word] absolute flex flex-col font-['Inter:Medium',sans-serif] font-medium h-[28px] justify-center leading-[0] left-[12px] not-italic text-[14px] top-[29px] w-[153px]"
               style={{ color: isLightBg ? '#484460' : '#fff' }}>
            <p className="whitespace-pre-wrap">
              <span className="leading-[normal]">v. {v}  |  </span>
              <span className="[word-break:break-word] font-['Inter:Bold',sans-serif] font-bold leading-[normal] not-italic"
                    style={{ color: isLightBg ? '#484460' : '#fff' }}>{safeStatus}</span>
            </p>
          </div>
        </div>

        {/* Like count */}
        <p className="-translate-x-full [word-break:break-word] absolute font-['Inter:Bold',sans-serif] font-bold h-[23px] leading-[20px] left-[242.89px] not-italic text-[13px] text-right text-white top-[329px] w-[70px]">
          {likeCount}
        </p>

        {/* Thumbs up */}
        <div className="absolute left-[246.89px] overflow-clip size-[22px] top-[324px] text-white/70" data-name="Thumbs-up--filled">
          <svg className="w-full h-full" fill="currentColor" viewBox="0 0 24 24">
            <path d="M2 9.75C2 9.33579 2.33579 9 2.75 9H5.5V20H2.75C2.33579 20 2 19.6642 2 19.25V9.75ZM7 20V9L13.1793 2.17058C13.4935 1.85639 14 2.07714 14 2.51452V7.5H20.2763C21.1626 7.5 21.831 8.29151 21.6835 9.16411L20.1835 18.1641C20.0698 18.8371 19.4852 19.3359 18.8024 19.3359H7Z" />
          </svg>
        </div>
      </div>
    </div>
  );
}

// ── Card back — metadata grid ────────────────────────────────────────────────
export function CardBack({ title, author, version, status, score, lastUsed }: {
  title: string; author: string; version: string; status: string; score: string; lastUsed: string;
}) {
  const statusColor =
    status === "Approved" || status === "approved" ? "text-[#8EC1B3]" :
    status === "Pending" || status === "pending" ? "text-[#FB8D67]" :
    status === "Drift" ? "text-red-400" : "text-gray-400";
  return (
    <div className="h-[359px] w-[278px] bg-[#1B2F3A] border border-[#8E98A8]/30 rounded-[10px] flex flex-col justify-center p-6 text-sm shadow-[0px_4px_4px_0px_rgba(0,0,0,0.25)]">
      <p className="text-base font-bold text-white mb-4 leading-tight font-['Inter:Bold']">{title}</p>
      <div className="grid grid-cols-2 gap-x-4 gap-y-2 text-xs">
        <span className="text-white/50">Author</span><span className="text-white font-medium">{author}</span>
        <span className="text-white/50">Version</span><span className="text-white">{version}</span>
        <span className="text-white/50">Status</span><span className={`font-semibold ${statusColor}`}>{status}</span>
        <span className="text-white/50">Score</span><span className="text-white">{score}</span>
        <span className="text-white/50">Last used</span><span className="text-white">{lastUsed}</span>
      </div>
      <p className="text-white/30 text-[10px] mt-4 italic">Double-click to open · Single-click to flip back</p>
    </div>
  );
}

// ── Toolbar — Create New / Popular / Templates / Groups / Docs ────────────────
export function Toolbar({ 
  onCreateNew, 
  searchValue, 
  onSearchChange,
  activeFilter = 'Templates',
  onFilterChange,
}: { 
  onCreateNew?: () => void; 
  searchValue?: string; 
  onSearchChange?: (v: string) => void;
  activeFilter?: string;
  onFilterChange?: (filter: string) => void;
}) {
  const filters = ['Popular', 'Templates', 'Groups', 'Docs'];
  
  return (
    <div className="content-stretch flex gap-[12px] items-center h-[42px]">
      <div className="bg-[rgba(96,121,118,0.5)] h-[42px] rounded-[10px] shrink-0 w-[44px]" />
      <div className="bg-[rgba(96,121,118,0.5)] h-[42px] rounded-[10px] shrink-0 w-[44px]" />
      <div className="bg-[rgba(96,121,118,0.5)] rounded-[10px] shrink-0 size-[42px]" />
      <div className="bg-[rgba(96,121,118,0.5)] content-stretch flex h-[42px] items-center justify-center rounded-[8px] shrink-0 w-[45px]" />
      <input
        type="text"
        data-tag="search-bar"
        value={searchValue || ""}
        onChange={(e) => onSearchChange?.(e.target.value)}
        placeholder="Search…"
        className="flex-[1_0_0] h-[42px] min-w-[120px] rounded-[6px] bg-[#ebebeb] shadow-[inset_0px_4px_4px_0px_rgba(0,0,0,0.25)] px-3 text-sm text-[#1a1a1a] placeholder:text-gray-400 outline-none border-0"
      />

      <button
        onClick={onCreateNew}
        className="bg-[rgba(80,114,116,0.75)] h-[42px] px-[5px] rounded-[8px] shrink-0 w-[150px] cursor-pointer hover:bg-[rgba(80,114,116,0.9)] transition-colors border border-[#758e87]"
      >
        <span className="font-bold text-[16px] text-white">Create New</span>
      </button>

      {filters.map((f) => {
        const isActive = activeFilter === f;
        return (
          <button
            key={f}
            onClick={() => onFilterChange?.(f)}
            className={`content-stretch flex h-[42px] items-center justify-center px-[10px] rounded-[8px] shrink-0 w-[120px] cursor-pointer transition-colors ${
              isActive
                ? 'bg-[#234354] border-2 border-[#8ec1b3]'
                : 'bg-[rgba(80,114,116,0.75)] border border-[#758e87] hover:bg-[rgba(80,114,116,0.9)]'
            }`}
          >
            <span className="font-bold text-[16px] text-white">{f}</span>
          </button>
        );
      })}
      <div className="bg-[rgba(117,142,135,0.5)] h-[42px] rounded-[8px] shrink-0 w-[46px]" />
    </div>
  );
}

// ── Agent card row — renders real DesignCards in a flex row ──────────────────
//
// ROW 0 (featured): 1 wide FeaturedCard (877px) + 2 narrow FlipCards (278px each)
//   Figma node: 40000177:6883
//   Slot 0 = FeaturedCard (hero, always visible)
//   Slot 1 = first agent (narrow FlipCard)
//   Slot 2 = second agent (narrow FlipCard)
// ROWS 1+: 5 narrow FlipCards per row
function AgentCardRow({ 
  agents, 
  startIdx, 
  onOpenPrompt 
}: { 
  agents: Array<{ 
    id: string; 
    title: string; 
    author?: string; 
    version?: number; 
    status?: string; 
    score?: string; 
    lastUsed?: string;
    createdAt?: string;
    category?: string;
    description?: string;
    username?: string;
    teamName?: string;
    likes?: number;
    tags?: string;
    comments?: number;
    message_count?: number;
  }>;
  startIdx: number;
  onOpenPrompt?: (id: string) => void;
}) {
  const isFirstRow = startIdx === 0;
  
  // Row 0: FeaturedCard (slot 0) + 2 narrow agent cards (slots 1-2)
  // Agents for narrow slots come from startIdx..startIdx+2 (first 2 agents)
  // Rows 1+: 5 narrow agent cards from startIdx..startIdx+4
  const narrowCount = isFirstRow ? 2 : 5;
  const narrowAgents = agents.slice(startIdx, startIdx + narrowCount);
  
  // Pad narrow slots
  const narrowSlots: Array<(typeof narrowAgents)[number] | null> = [...narrowAgents];
  while (narrowSlots.length < narrowCount) {
    narrowSlots.push(null);
  }

  return (
    <div
      data-lit-id="agent-card-row"
      data-lit-type="card-grid-row"
      data-lit-description="Responsive card row — wraps from 3 to 2 to 1 column"
      className="content-stretch flex flex-wrap gap-[20px] items-start overflow-clip relative shrink-0"
    >
      {isFirstRow && agents.length === 0 ? (
        // First row, no agents — show wide empty state
        <div className="h-[359px] w-full max-w-[877px] bg-white border-2 border-dashed border-gray-300 rounded-[10px] flex flex-col items-center justify-center gap-4">
          <svg className="w-12 h-12 text-gray-300" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M12 4.5v15m7.5-7.5h-15" />
          </svg>
          <p className="text-gray-400 font-medium text-sm">No active prompt sessions</p>
          <p className="text-gray-300 text-xs">Create your first agent package to get started</p>
        </div>
      ) : isFirstRow ? (
        // Slot 0: FeaturedCard — hero card, always shown when agents exist
        <FeaturedCard
          id=""
          subtitle="Enterprise Prompt Portal"
          headline="Unlock ChatGPT God‑Mode in 20 Minutes"
          teamHandle={agents[0]?.username}
          teamName={agents[0]?.teamName}
          onOpenPrompt={onOpenPrompt}
        />
      ) : null}
      {narrowSlots.map((agent, i) => {
        if (!agent) {
          return <div key={`empty-${i}`} className="h-[359px] w-[278px] border border-dashed border-gray-200 rounded-[10px]" />;
        }
        
        // Narrow FlipCard (278px) — Lit agent-card-element
        return (
          <FlipCard
            key={agent.id}
            cardId={agent.id}
            onOpenPrompt={onOpenPrompt}
            front={React.createElement('agent-card-element', {
              id: agent.id,
              title: agent.title,
              category: agent.category || '',
              description: agent.description || '',
              username: agent.username || agent.author || '',
              'team-name': agent.teamName || '',
              version: agent.version || agent.message_count || 1,
              status: agent.status || 'Active',
              likes: agent.likes ?? 0,
              'model-name': '',
              'last-used': agent.lastUsed || '',
              'created-at': agent.createdAt || '',
            })}
            back={
              <CardBack
                title={agent.title}
                author={agent.author || "You"}
                version={`v${agent.version || agent.message_count || 1}`}
                status={agent.status || "Active"}
                score={agent.score || "—"}
                lastUsed={agent.lastUsed || "—"}
              />
            }
          />
        );
      })}
    </div>
  );
}

// ── Main export — delegates to AgentRow with flex-wrap ──────────────────────
export function Frame29({ onOpenPrompt, searchValue, agents, onCreateNew, onSearchChange, activeFilter = 'Templates', onFilterChange, onOpenDoc }: {
  onOpenPrompt?: (id: string) => void;
  searchValue?: string;
  onSearchChange?: (v: string) => void;
  activeFilter?: string;
  onFilterChange?: (filter: string) => void;
  onOpenDoc?: (doc: StorybookDoc, content: string) => void;
  agents?: Array<{ 
    id: string; 
    title: string; 
    author?: string; 
    version?: number; 
    status?: string; 
    score?: string; 
    lastUsed?: string;
    createdAt?: string;
    category?: string;
    description?: string;
    username?: string;
    teamName?: string;
    likes?: number;
    tags?: string;
    comments?: number;
    message_count?: number;
  }>;
  onCreateNew?: () => void;
}) {
  const [page, setPage] = useState(0);
  const [isMobile, setIsMobile] = useState(false);
  const toolbarRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const check = () => setIsMobile(window.innerWidth < 480);
    check();
    window.addEventListener("resize", check);
    return () => window.removeEventListener("resize", check);
  }, []);

  const agentList = agents || [];
  const filtered = searchValue
    ? agentList.filter((a) => a.title.toLowerCase().includes(searchValue.toLowerCase()))
    : agentList;

  const PER_PAGE = 7;
  const totalPages = isMobile ? 1 : Math.max(1, Math.ceil(filtered.length / PER_PAGE));
  const pageAgents = isMobile ? filtered.slice(0, 10) : filtered.slice(page * PER_PAGE, (page + 1) * PER_PAGE);

  const scrollToolbar = useCallback((dir: "left" | "right") => {
    toolbarRef.current?.scrollBy({ left: dir === "left" ? -300 : 300, behavior: "smooth" });
  }, []);

  // Build rows for AgentRow: row 0 has FeaturedCard + 2 narrow, rest have 5 narrow
  const rows: Array<{ agents: typeof pageAgents; startIdx: number }> = [];
  rows.push({ agents: pageAgents, startIdx: 0 });
  if (pageAgents.length > 2) rows.push({ agents: pageAgents, startIdx: 2 });
  let idx = 7;
  while (idx < pageAgents.length) {
    rows.push({ agents: pageAgents, startIdx: idx });
    idx += 5;
  }

  return (
    <div className="w-full flex flex-col gap-4">

      {/* Single continuous flex-wrap flow — cards snake naturally */}
      {activeFilter === 'Docs' ? (
        <div className="content-stretch flex flex-wrap gap-[20px] items-start justify-center w-full">
          {STORYBOOK_DOCS.length > 0 ? (
            STORYBOOK_DOCS.map((doc) => (
              <StorybookDocCard
                key={doc.id}
                doc={doc}
                onOpen={onOpenDoc}
              />
            ))
          ) : (
            <div className="h-[359px] w-[877px] max-w-full bg-white border-2 border-dashed border-gray-300 rounded-[10px] flex flex-col items-center justify-center gap-4">
              <p className="text-gray-400 font-medium text-sm">No documentation files found</p>
              <p className="text-gray-300 text-xs">Add .mdx or .md files to the storybook directory</p>
            </div>
          )}
        </div>
      ) : (
      <>
      <div className="content-stretch flex flex-wrap gap-[20px] items-start justify-center w-full">
        {pageAgents.length > 0 ? (
          <FeaturedCard
            id=""
            subtitle="Enterprise Prompt Portal"
            headline="Unlock ChatGPT God‑Mode in 20 Minutes"
            teamHandle={pageAgents[0]?.username}
            teamName={pageAgents[0]?.teamName}
            onOpenPrompt={onOpenPrompt}
          />
        ) : (
          <div className="h-[359px] w-[877px] max-w-full bg-white border-2 border-dashed border-gray-300 rounded-[10px] flex flex-col items-center justify-center gap-4">
            <p className="text-gray-400 font-medium text-sm">No active prompt sessions</p>
            <p className="text-gray-300 text-xs">Create your first agent package to get started</p>
          </div>
        )}
        {pageAgents.map((agent, i) => (
          <FlipCard
            key={agent.id}
            cardId={agent.id}
            onOpenPrompt={onOpenPrompt}
            front={React.createElement('agent-card-element', {
              id: agent.id,
              title: agent.title,
              category: agent.category || '',
              description: agent.description || '',
              username: agent.username || agent.author || '',
              'team-name': agent.teamName || '',
              version: agent.version || agent.message_count || 1,
              status: agent.status || 'Active',
              likes: agent.likes ?? 0,
              'model-name': '',
              'last-used': agent.lastUsed || '',
              'created-at': agent.createdAt || '',
            })}
            back={<CardBack title={agent.title} author={agent.author || "You"} version={`v${agent.version || agent.message_count || 1}`} status={agent.status || "Active"} score={agent.score || "—"} lastUsed={agent.lastUsed || "—"} />}
          />
        ))}
      </div>

      {/* Pagination */}
      {!isMobile && totalPages > 1 && (
        <div className="flex items-center justify-center gap-4 py-2">
          <button onClick={() => setPage((p) => Math.max(0, p - 1))} disabled={page === 0} className="w-10 h-10 rounded-full flex items-center justify-center bg-white border border-gray-200 text-gray-600 hover:bg-gray-50 disabled:opacity-30 disabled:cursor-not-allowed transition-all shadow-sm" aria-label="Previous page">
            <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" /></svg>
          </button>
          <span className="text-sm text-gray-500 font-medium min-w-[60px] text-center">{page + 1} / {totalPages}</span>
          <button onClick={() => setPage((p) => Math.min(totalPages - 1, p + 1))} disabled={page >= totalPages - 1} className="w-10 h-10 rounded-full flex items-center justify-center bg-white border border-gray-200 text-gray-600 hover:bg-gray-50 disabled:opacity-30 disabled:cursor-not-allowed transition-all shadow-sm" aria-label="Next page">
            <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" /></svg>
          </button>
        </div>
      )}
      </>
      )}
    </div>
  );
}
